In [3]:
import numpy as np

## NUMPY ARRAY

In [4]:
my_list = [10,20,30]

In [5]:
type(my_list)

list

In [6]:
np.array(my_list)

array([10, 20, 30])

In [7]:
type(my_list)

list

In [8]:
matrix_list = [[10,20,30], [40,50,60], [70,80,90]]

In [9]:
matrix_list[1][0]

40

In [10]:
np.array(matrix_list)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

## ARANGE

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [31]:
my_numpy_list = np.arange(0,30)
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## ZEROS

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ONES

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## LINSPACE

In [19]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

## EYE

In [20]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## RANDOM

In [21]:
np.random.randn(5)

array([-0.13244733,  0.63715061, -1.50792847, -1.72305597, -0.37907513])

In [22]:
np.random.randn(5,5)

array([[-0.24094227, -1.98548524, -0.51339004,  0.42481846, -0.25005464],
       [ 2.16141975,  0.24440912, -0.29302635, -1.17406254,  0.36572299],
       [ 1.47397256, -0.47439634,  0.49090543, -0.64441596,  0.58025745],
       [ 0.62336815, -0.56202648, -0.28871266, -1.10906693, -0.60712049],
       [ 1.18299327, -0.35347083, -0.13917555,  0.11896451,  0.39566275]])

In [23]:
np.random.randint(1,10)

7

In [29]:
np.random.randint(1,10,5)

array([3, 8, 3, 2, 5])

## NUMPY ARRAY METHODS

In [32]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [33]:
my_numpy_list.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [34]:
my_numpy_list.max()

29

In [37]:
my_numpy_list.min()

0

In [38]:
my_numpy_list.sum()

435

In [39]:
my_numpy_list.argmax()

29

In [40]:
my_numpy_list.argmin()

0

In [41]:
my_reshape_array = my_numpy_list.reshape(5,6)

In [42]:
my_reshape_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [43]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])