In [3]:
import numpy as np

In [5]:
my_list = np.arange(0,15)

In [6]:
my_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## NUMPY INDEXES

In [7]:
my_list[5]

5

In [8]:
my_list[5:10]

array([5, 6, 7, 8, 9])

In [9]:
my_list[5:10] = 0

In [10]:
my_list

array([ 0,  1,  2,  3,  4,  0,  0,  0,  0,  0, 10, 11, 12, 13, 14])

In [12]:
my_other_list = np.arange(0,24)

In [13]:
my_other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
slicing_other_list = my_other_list[5:10]

In [20]:
slicing_other_list

array([5, 6, 7, 8, 9])

In [21]:
my_other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [22]:
type(slicing_other_list)

numpy.ndarray

In [23]:
slicing_other_list[:]

array([5, 6, 7, 8, 9])

In [25]:
slicing_other_list[:] = 100

In [26]:
slicing_other_list

array([100, 100, 100, 100, 100])

In [27]:
my_other_list

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [28]:
example_list = np.arange(0,24)

In [29]:
example_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
example_list_copy = example_list.copy()

In [31]:
example_list_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [32]:
slicing_example_list_copy = example_list_copy[5:10]

In [34]:
slicing_example_list_copy

array([5, 6, 7, 8, 9])

In [35]:
slicing_example_list_copy[:] = 100

In [36]:
slicing_example_list_copy

array([100, 100, 100, 100, 100])

In [37]:
example_list_copy

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [38]:
example_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## NUMPY MATRIX

In [42]:
my_new_list = np.arange(0,9)

In [43]:
my_new_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
my_matrix = my_new_list.reshape(3,3)

In [45]:
my_matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
my_matrix[0]

array([0, 1, 2])

In [47]:
my_matrix[1,2]

5

In [48]:
my_matrix[1:,1:]

array([[4, 5],
       [7, 8]])

In [49]:
my_matrix[0,1:]

array([1, 2])

In [50]:
my_matrix[1:,1]

array([4, 7])

In [63]:
my_other_new_list = np.arange(0,25)

In [64]:
my_other_new_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [65]:
my_other_new_matrix = my_other_new_list.reshape(5,5)

In [67]:
my_other_new_matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [70]:
my_other_new_matrix[0,2]

2

In [68]:
my_other_new_matrix[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [71]:
my_other_new_matrix[[4,2,1]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9]])

## NUMPY OPERATIONS

In [79]:
my_newest_list = np.random.randint(1,100,20)

In [80]:
my_newest_list

array([11, 57, 27, 15, 87, 14, 86,  8, 10, 35,  9, 35, 29, 74, 22,  9,  8,
       51, 28,  1])

In [81]:
my_newest_list > 24

array([False,  True,  True, False,  True, False,  True, False, False,
        True, False,  True,  True,  True, False, False, False,  True,
        True, False])

In [82]:
result_list = my_newest_list > 20

In [83]:
result_list

array([False,  True,  True, False,  True, False,  True, False, False,
        True, False,  True,  True,  True,  True, False, False,  True,
        True, False])

In [84]:
my_newest_list[result_list]

array([57, 27, 87, 86, 35, 35, 29, 74, 22, 51, 28])

In [85]:
my_newest_list[my_newest_list > 20]

array([57, 27, 87, 86, 35, 35, 29, 74, 22, 51, 28])

In [87]:
my_newest_list

array([11, 57, 27, 15, 87, 14, 86,  8, 10, 35,  9, 35, 29, 74, 22,  9,  8,
       51, 28,  1])

In [86]:
my_newest_list + my_newest_list

array([ 22, 114,  54,  30, 174,  28, 172,  16,  20,  70,  18,  70,  58,
       148,  44,  18,  16, 102,  56,   2])

In [89]:
my_newest_list * 3

array([ 33, 171,  81,  45, 261,  42, 258,  24,  30, 105,  27, 105,  87,
       222,  66,  27,  24, 153,  84,   3])

In [90]:
my_newest_list

array([11, 57, 27, 15, 87, 14, 86,  8, 10, 35,  9, 35, 29, 74, 22,  9,  8,
       51, 28,  1])

In [91]:
my_newest_list * my_newest_list

array([ 121, 3249,  729,  225, 7569,  196, 7396,   64,  100, 1225,   81,
       1225,  841, 5476,  484,   81,   64, 2601,  784,    1])

In [92]:
my_newest_list ** 2

array([ 121, 3249,  729,  225, 7569,  196, 7396,   64,  100, 1225,   81,
       1225,  841, 5476,  484,   81,   64, 2601,  784,    1])

In [93]:
my_newest_list - my_newest_list

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
my_newest_list / my_newest_list # eğer dizide 0 olursa invalid value hatası alırız ama 0 olan değerler için nan yazılır.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [98]:
np.sqrt(my_newest_list)

array([3.31662479, 7.54983444, 5.19615242, 3.87298335, 9.32737905,
       3.74165739, 9.2736185 , 2.82842712, 3.16227766, 5.91607978,
       3.        , 5.91607978, 5.38516481, 8.60232527, 4.69041576,
       3.        , 2.82842712, 7.14142843, 5.29150262, 1.        ])

In [99]:
np.max(my_newest_list)

87

In [101]:
np.min(my_newest_list)

1